import { GoogleGenAI } from "@google/genai";

const ai = new GoogleGenAI({ apiKey: process.env.API_KEY });

/**
 * Generates stylistic feedback comparing the original image with the generated one.
 */
export const generateStylistFeedback = async (originalBase64: string, generatedBase64: string, prompt: string): Promise<string> => {
  try {
    const cleanOriginal = originalBase64.replace(/^data:image\/(png|jpeg|jpg|webp);base64,/, '');
    const cleanGenerated = generatedBase64.replace(/^data:image\/(png|jpeg|jpg|webp);base64,/, '');

    const response = await ai.models.generateContent({
      model: 'gemini-2.0-flash',
      contents: {
        role: 'user',
        parts: [
          { text: `Ti si vrhunski, motivacioni, ali i potpuno iskreni hair stilista. Klijent je upravo isprobao novu frizuru koristeći AI. Tražena frizura je: "${prompt}".\nPrva slika je originalna slika (pre), a druga slika je generisana nova frizura (posle).\n\nTvoj zadatak je da analiziraš sliku klijenta (oblik lica, ten, crte lica) i kažeš svoje mišljenje kako se ova nova frizura uklapa.\nBUDI ISKREN: Objasni šta ti se sviđa, a šta bi možda moglo bolje (npr. da li otvara lice, da li boja odgovara tenu). Ako izgleda ok reci to, a ako ne stoji baš najbolje, slobodno to reci na ljubazan i motivišući način i daj neki kratak predlog za razmišljanje.\n\nNa kraju, OBAVEZNO završi savet sličnom porukom: "Izgleda super za eksperimentisanje! Probaj još frizura ovde i obavezno se posavetuj sa svojim frizerom pre nego što se odlučiš da napraviš pravu promenu."\n\nObrati se direktno klijentu (na "ti") sa puno energije, stila i ljubavi prema kosi. Ne koristi generične fraze. Ograniči savet na 2-3 kratka paragrafa (na srpskom/hrvatskom/bosanskom).` },
          { inlineData: { data: cleanOriginal, mimeType: 'image/jpeg' } },
          { inlineData: { data: cleanGenerated, mimeType: 'image/jpeg' } }
        ]
      }
    });

    return response.text || "Nismo uspeli da generišemo savet u ovom trenutku.";
  } catch (error) {
    console.error("Gemini Stylist Feedback Error:", error);
    throw error;
  }
};

/**
 * Edits an image based on a text prompt using Gemini 2.5 Flash Image.
 * 
 * @param imageBase64 - The base64 string of the source image (without data URI prefix ideally, but we handle cleaning).
 * @param prompt - The text instruction for the edit (e.g., "Make it a corporate headshot").
 * @returns The base64 string of the generated image.
 */
export const generateHeadshot = async (imageBase64: string, prompt: string): Promise<string> => {
  try {
    // Ensure clean base64 string
    const cleanBase64 = imageBase64.replace(/^data:image\/(png|jpeg|jpg|webp);base64,/, '');

    const response = await ai.models.generateContent({
      model: 'gemini-2.5-flash-image',
      contents: {
        parts: [
          {
            inlineData: {
              data: cleanBase64,
              mimeType: 'image/jpeg', // Assuming JPEG for simplicity, or we could detect.
            },
          },
          {
            // Strengthening the prompt to ensure the face is preserved and no unwanted details are added.
            text: `${prompt} Important: Keep the person's face, facial features, skin texture, and expression exactly the same. DO NOT add any new marks, moles, freckles, wrinkles, or blemishes that are not present in the original picture. Completely preserve the original facial identity. Only change the hair/style as requested. Photorealistic, high quality.`,
          },
        ],
      },
      // Note: responseMimeType and responseSchema are NOT supported for this model.
      // We do not use them.
    });

    let generatedImageBase64 = '';

    // Iterate through parts to find the image
    if (response.candidates?.[0]?.content?.parts) {
      for (const part of response.candidates[0].content.parts) {
        if (part.inlineData && part.inlineData.data) {
          generatedImageBase64 = part.inlineData.data;
          break; // Found the image
        }
      }
    }

    if (!generatedImageBase64) {
      throw new Error("No image generated by the model. It might have returned only text.");
    }

    return `data:image/png;base64,${generatedImageBase64}`;

  } catch (error) {
    console.error("Gemini API Error:", error);
    throw error;
  }
};